export const INSCRIPCIONES = [
  // ─── PÚBLICAS (40) ────────────────────────────────
  // Existentes
  {
    id: 'la_llama_viva',
    nombre: 'La Llama Viva',
    descripcion: '3 agonías completas seguidas. El fuego del agon no conoce la extinción.',
    condicion: 'Completa 3 días perfectos consecutivos.',
    icono: '🔥',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'agua_sagrada',
    nombre: 'El Agua Sagrada',
    descripcion: '7 días de pureza. El cuerpo del agonista no acepta lo que lo debilita.',
    condicion: 'Registra solo agua durante 7 días totales.',
    icono: '💧',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'semana_olimpica',
    nombre: 'La Semana Olímpica',
    descripcion: 'Todas las pruebas, todos los días, durante 7 días. El Altis lo inscribe en dorado.',
    condicion: 'Completa 7 días perfectos consecutivos.',
    icono: '👑',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'furia_del_agon',
    nombre: 'La Furia del Agon',
    descripcion: 'Cinco sesiones de gimnasio en una semana. Más allá de lo que el contrato exige.',
    condicion: 'Registra 5 sesiones de gym en una misma semana.',
    icono: '⚡',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'el_heraldo',
    nombre: 'El Heraldo',
    descripcion: 'El agonista que inicia antes que el sol no teme al día que viene.',
    condicion: 'Registra una prueba antes de las 7am.',
    icono: '🌅',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'filosofo_del_agon',
    nombre: 'El Filósofo del Agon',
    descripcion: 'Cien páginas leídas. El agonista que solo entrena el cuerpo es a medias.',
    condicion: 'Acumula 100 páginas leídas en total.',
    icono: '📜',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'ayuno_de_hierro',
    nombre: 'El Ayuno de Hierro',
    descripcion: '14 días sin comida rápida. La disciplina del cuerpo empieza en la boca.',
    condicion: 'Registra 14 días sin comida rápida en total.',
    icono: '💀',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'imparable',
    nombre: 'Imparable',
    descripcion: '14 agonías completas. El agonista que llega a la mitad ya no puede ser detenido.',
    condicion: 'Acumula 14 días perfectos totales.',
    icono: '🚀',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'gemelos_del_agon',
    nombre: 'Los Gemelos del Agon',
    descripcion: 'Ambos agonistas completan el mismo día perfecto. El agon los igualó.',
    condicion: 'Ambos agonistas completan un día perfecto el mismo día.',
    icono: '🤝',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'la_remontada',
    nombre: 'La Remontada',
    descripcion: '300 kleos de desventaja. Recuperados. El agon no termina hasta que termina.',
    condicion: 'Recupera 300 kleos de desventaja frente al antagonista.',
    icono: '📉',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'el_gran_agon',
    nombre: 'El Gran Agon',
    descripcion: '29 días. Todas las pruebas. El Altis te inscribe para siempre.',
    condicion: 'Completa todos los 29 días del Gran Agon.',
    icono: '🏛️',
    tipo: 'publica' as const,
    secreto: false,
  },
  // Nuevas públicas
  {
    id: 'el_iniciado',
    nombre: 'El Iniciado',
    descripcion: 'El primer día perfecto. El Altis te inscribe por primera vez.',
    condicion: 'Completa tu primer día perfecto.',
    icono: '🌱',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'el_primer_paso',
    nombre: 'El Primer Paso',
    descripcion: 'La primera vez que cruzaste esa línea. El Altis lo registra.',
    condicion: 'Registra 10.000+ pasos por primera vez.',
    icono: '👟',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'el_primer_combate',
    nombre: 'El Primer Combate',
    descripcion: 'El primer acto de combate físico del Gran Agon.',
    condicion: 'Registra tu primera sesión de gym.',
    icono: '🏋️',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'la_primera_carrera',
    nombre: 'La Primera Carrera',
    descripcion: 'No es gym — es movimiento distinto, disciplina distinta. El Altis lo distingue.',
    condicion: 'Registra tu primera sesión de cardio.',
    icono: '🏃',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'el_bautismo',
    nombre: 'El Bautismo',
    descripcion: 'El primer día sin ceder. El toggle marcado, el cuerpo respetado.',
    condicion: 'Completa tu primer día de solo agua.',
    icono: '💧',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'el_despertar_de_apolo',
    nombre: 'El Despertar de Apolo',
    descripcion: 'El agonista que entrena solo el cuerpo termina el agon a medias.',
    condicion: 'Registra 10+ páginas leídas por primera vez.',
    icono: '📖',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'el_madrugador',
    nombre: 'El Madrugador',
    descripcion: 'No esperó al final del día. Tres veces el Altis lo encontró listo antes del mediodía.',
    condicion: 'Completa las 7 pruebas antes del mediodía, 3 veces.',
    icono: '🌄',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'la_bestia',
    nombre: 'La Bestia',
    descripcion: 'El contrato no lo pedía. El agonista lo hizo igual. Cinco veces.',
    condicion: 'Registra gym y cardio el mismo día, 5 veces totales.',
    icono: '🦁',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'el_estoico',
    nombre: 'El Estoico',
    descripcion: 'Cinco días seguidos. No fue suerte — fue decisión repetida.',
    condicion: 'Completa 5 días perfectos consecutivos.',
    icono: '🗿',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'el_caminante',
    nombre: 'El Caminante',
    descripcion: 'No es una racha — es consistencia acumulada. El agonista que siempre avanza.',
    condicion: 'Registra 10.000+ pasos en 14 días totales.',
    icono: '🚶',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'el_discipulo_de_morfeo',
    nombre: 'El Discípulo de Morfeo',
    descripcion: 'La recuperación también es combate. El Altis lo inscribe.',
    condicion: 'Registra 7+ horas de sueño en 14 días totales.',
    icono: '🌙',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'el_punto_sin_retorno',
    nombre: 'El Punto Sin Retorno',
    descripcion: 'El ecuador. Quedan 15 días. El Altis celebra que sigues en pie.',
    condicion: 'Completa todas las pruebas del día 14.',
    icono: '⚖️',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'el_mil_kleos',
    nombre: 'El Mil Kleos',
    descripcion: 'Mil actos de disciplina convertidos en un número.',
    condicion: 'Acumula 1.000 kleos totales.',
    icono: '💎',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'los_dos_mil',
    nombre: 'Los Dos Mil',
    descripcion: 'Los números no mienten y este lo dice todo.',
    condicion: 'Acumula 2.000 kleos totales.',
    icono: '💎',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'la_gloria_maxima',
    nombre: 'La Gloria Máxima',
    descripcion: '3.000 kleos no se acumulan por accidente.',
    condicion: 'Acumula 3.000 kleos totales.',
    icono: '🏆',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'los_diez_del_altis',
    nombre: 'Los Diez del Altis',
    descripcion: 'El Altis sumó y llegó a 10. No importa el orden.',
    condicion: 'Acumula 10 días perfectos totales.',
    icono: '🔟',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'los_veinte_del_olimpo',
    nombre: 'Los Veinte del Olimpo',
    descripcion: 'A este punto el antagonista ya sabe que no fue casualidad.',
    condicion: 'Acumula 20 días perfectos totales.',
    icono: '🌟',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'el_lector_voraz',
    nombre: 'El Lector Voraz',
    descripcion: 'Un libro entero, quizás dos. El agonista que también entrena la mente.',
    condicion: 'Acumula 200 páginas leídas en total.',
    icono: '📚',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'la_biblioteca_del_agon',
    nombre: 'La Biblioteca del Agon',
    descripcion: 'Has leído más en 29 días que la mayoría en un año.',
    condicion: 'Acumula 300 páginas leídas en total.',
    icono: '📚',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'el_atleta_forjado',
    nombre: 'El Atleta Forjado',
    descripcion: 'Aspirante ya no. El primer escalón del Olimpo tiene nombre.',
    condicion: 'Alcanza el nivel Atleta (150 kleos).',
    icono: '🏃',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'el_agonista_forjado',
    nombre: 'El Agonista Forjado',
    descripcion: 'Ya no eres solo alguien que empezó. Eres alguien que sostiene.',
    condicion: 'Alcanza el nivel Agonista (350 kleos).',
    icono: '⚡',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'el_campeon_del_altis',
    nombre: 'El Campeón del Altis',
    descripcion: 'No viniste a participar. Viniste a ganar.',
    condicion: 'Alcanza el nivel Campeón (900 kleos).',
    icono: '⚔️',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'el_heroe_del_altis',
    nombre: 'El Héroe del Altis',
    descripcion: 'No como título honorífico — como descripción de lo que está ocurriendo.',
    condicion: 'Alcanza el nivel Héroe (1.300 kleos).',
    icono: '🔥',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'el_semidios',
    nombre: 'El Semidiós',
    descripcion: 'En la frontera entre lo humano y lo olímpico. Los dioses te reconocen.',
    condicion: 'Alcanza el nivel Semidiós (1.800 kleos).',
    icono: '🦅',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'el_olimpico',
    nombre: 'El Olímpico',
    descripcion: 'Los dioses te reciben no como visitante sino como igual.',
    condicion: 'Alcanza el nivel Olímpico (2.400 kleos).',
    icono: '⭐',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'la_constancia',
    nombre: 'La Constancia',
    descripcion: 'El Altis no premia solo el esfuerzo máximo. Premia la repetición sin fisuras.',
    condicion: 'Completa la misma prueba 10 días consecutivos.',
    icono: '🔗',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'el_rey_del_cardio',
    nombre: 'El Rey del Cardio',
    descripcion: 'El contrato pedía esto. Tú lo entregaste exacto. Tres semanas sin fallar.',
    condicion: 'Completa 3 sesiones de cardio por semana durante 3 semanas consecutivas.',
    icono: '👑',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'el_purista',
    nombre: 'El Purista',
    descripcion: '21 días. El Altis suma sin preguntar cuánto costó cada uno.',
    condicion: 'Registra 21 días sin comida rápida en total.',
    icono: '🛡️',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'la_pureza_del_agua',
    nombre: 'La Pureza del Agua',
    descripcion: 'El toggle se marcó 21 veces. El Altis no pregunta si fue fácil.',
    condicion: 'Registra 21 días de solo agua en total.',
    icono: '💧',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'el_iniciado_de_la_ciudad',
    nombre: 'El Iniciado de la Ciudad',
    descripcion:
      'La Ciudad de Olimpia abrió sus puertas. El Altis registra el primer paso dentro de sus muros.',
    condicion: 'Alcanza rango Conocido en tu primera facción.',
    icono: '🏛️',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'el_reconocido',
    nombre: 'El Reconocido',
    descripcion:
      'Ya no eres un extraño en la Ciudad. Una facción sabe tu nombre y lo que vales.',
    condicion: 'Alcanza rango Aliado en cualquier facción.',
    icono: '🤝',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'campeon_de_la_ciudad',
    nombre: 'Campeón de la Ciudad',
    descripcion:
      'El rango más alto que la Ciudad otorga. No todos llegan. El Altis inscribe a los que sí.',
    condicion: 'Alcanza rango Campeón en cualquier facción.',
    icono: '⚜️',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'la_disputa',
    nombre: 'La Disputa',
    descripcion:
      'Dos agonistas reclamaron el mismo trono. El agon no admite dos campeones en el mismo lugar.',
    condicion: 'Inicia una Disputa de Campeón.',
    icono: '⚔️',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'el_forjado_en_crisis',
    nombre: 'El Forjado en Crisis',
    descripcion: 'La primera crisis llegó. El agonista estuvo ahí para recibirla.',
    condicion: 'Participa en tu primera Crisis de Ciudad.',
    icono: '🌋',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'el_extraordinario',
    nombre: 'El Extraordinario',
    descripcion:
      'El agon ofreció más de lo que el contrato exigía. El agonista aceptó.',
    condicion: 'Completa tu primera prueba extraordinaria.',
    icono: '✨',
    tipo: 'publica' as const,
    secreto: false,
  },
  {
    id: 'mas_alla_de_lo_ordinario',
    nombre: 'Más Allá de lo Ordinario',
    descripcion:
      'Diez veces el agon llamó fuera del contrato. Diez veces el agonista respondió.',
    condicion: 'Completa 10 pruebas extraordinarias totales.',
    icono: '🌠',
    tipo: 'publica' as const,
    secreto: false,
  },

  // ─── SECRETAS (20) ────────────────────────────────
  {
    id: 'guardian_de_la_noche',
    nombre: 'El Guardián de la Noche',
    descripcion: 'El agonista que el agon encuentra despierto a las 3am. Su llama nunca duerme.',
    condicion: 'Registra actividad entre las 2am y las 5am.',
    icono: '🌙',
    tipo: 'secreta' as const,
    secreto: true,
  },
  {
    id: 'precision_del_sabio',
    nombre: 'La Precisión del Sabio',
    descripcion: 'Exactamente 8 horas de sueño, tres días seguidos. El agonista que domina hasta el descanso.',
    condicion: 'Registra exactamente 8 horas de sueño 3 días consecutivos.',
    icono: '😴',
    tipo: 'secreta' as const,
    secreto: true,
  },
  {
    id: 'la_piedra_del_agon',
    nombre: 'La Piedra del Agon',
    descripcion: 'Ambos fallan la misma prueba el mismo día. El agon los quebró igual.',
    condicion: 'Ambos agonistas fallan la misma prueba el mismo día.',
    icono: '🪨',
    tipo: 'secreta' as const,
    secreto: true,
  },
  {
    id: 'la_ekecheiria',
    nombre: 'La Ekecheiria',
    descripcion: 'La tregua sagrada fue invocada. Hasta los dioses se detienen ante la lesión.',
    condicion: 'Invoca La Ekecheiria.',
    icono: '⚖️',
    tipo: 'secreta' as const,
    secreto: true,
  },
  {
    id: 'agonista_invisible',
    nombre: 'El Agonista Invisible',
    descripcion: 'Tres días completos sin una sola palabra en el Ágora. El kleos se acumula en silencio.',
    condicion: 'Completa 3 días perfectos sin publicar nada en el Ágora.',
    icono: '👻',
    tipo: 'secreta' as const,
    secreto: true,
  },
  {
    id: 'senalamiento_perfecto',
    nombre: 'El Señalamiento Perfecto',
    descripcion: 'Señalaste al antagonista el día que ya iba a caer. El agon tiene sentido del humor.',
    condicion: 'Señala al antagonista el día que completa 0 pruebas.',
    icono: '🎯',
    tipo: 'secreta' as const,
    secreto: true,
  },
  {
    id: 'mas_alla_del_contrato',
    nombre: 'Más Allá del Contrato',
    descripcion: 'Cardio siete días seguidos. El contrato pedía tres por semana. El agon pide más.',
    condicion: 'Registra cardio 7 días consecutivos.',
    icono: '🏃',
    tipo: 'secreta' as const,
    secreto: true,
  },
  {
    id: 'lengua_del_agon',
    nombre: 'La Lengua del Agon',
    descripcion: 'Diez provocaciones en un día. El agonista que no puede callarse merece su propia inscripción.',
    condicion: 'Envía 10 provocaciones en un solo día.',
    icono: '🧂',
    tipo: 'secreta' as const,
    secreto: true,
  },
  {
    id: 'el_insomnio',
    nombre: 'El Insomnio del Agonista',
    descripcion: 'El agonista que no cierra el día sin cumplir. Tres veces después de medianoche.',
    condicion: 'Registra actividad después de medianoche 3 veces.',
    icono: '🦉',
    tipo: 'secreta' as const,
    secreto: true,
  },
  {
    id: 'la_herejia',
    nombre: 'La Herejía',
    descripcion: 'La mejor respuesta no fue una palabra — fueron las siete pruebas.',
    condicion: 'Ser señalado y completar las 7 pruebas ese mismo día.',
    icono: '⚡',
    tipo: 'secreta' as const,
    secreto: true,
  },
  {
    id: 'la_venganza',
    nombre: 'La Venganza',
    descripcion: 'El antagonista que disparó el señalamiento perdió la semana. El agon tiene sentido del humor.',
    condicion: 'Ser señalado y ganar la Hegemonía esa misma semana.',
    icono: '🗡️',
    tipo: 'secreta' as const,
    secreto: true,
  },
  {
    id: 'el_primero_del_olimpo',
    nombre: 'El Primero del Olimpo',
    descripcion: 'Marcas la sesión antes de las 5:30am. El Altis nota la hora.',
    condicion: 'Registra actividad antes de las 5:30am.',
    icono: '🌠',
    tipo: 'secreta' as const,
    secreto: true,
  },
  {
    id: 'la_cadena_de_oro',
    nombre: 'La Cadena de Oro',
    descripcion: 'El Altis no anuncia esto en ningún lado. Simplemente aparece cuando el contador llega a 10.',
    condicion: 'Completa 10 días perfectos consecutivos.',
    icono: '⛓️',
    tipo: 'secreta' as const,
    secreto: true,
  },
  {
    id: 'el_hijo_de_ares',
    nombre: 'El Hijo de Ares',
    descripcion: 'Ares dejó de criticarte. Eso dice más que cualquier inscripción.',
    condicion: 'Registra gym 4 sesiones por semana durante 3 semanas consecutivas.',
    icono: '🔱',
    tipo: 'secreta' as const,
    secreto: true,
  },
  {
    id: 'el_monje_del_altis',
    nombre: 'El Monje del Altis',
    descripcion: 'El Ágora existe. Tú elegiste no usarla. El Altis nota el silencio.',
    condicion: 'Completa 5 días perfectos sin publicar nada en el Ágora.',
    icono: '🧘',
    tipo: 'secreta' as const,
    secreto: true,
  },
  {
    id: 'el_constante',
    nombre: 'El Constante',
    descripcion: 'El Altis valora la presencia sobre la perfección. 29 días, 29 registros.',
    condicion: 'Registra al menos 1 prueba cada uno de los 29 días.',
    icono: '🧱',
    tipo: 'secreta' as const,
    secreto: true,
  },
  {
    id: 'el_cuerpo_sin_limites',
    nombre: 'El Cuerpo sin Límites',
    descripcion: 'Siete días de doble combate. El Altis no lo esperaba.',
    condicion: 'Registra gym y cardio el mismo día, 7 veces totales.',
    icono: '💪',
    tipo: 'secreta' as const,
    secreto: true,
  },
  {
    id: 'el_inmortal',
    nombre: 'El Inmortal',
    descripcion: 'El nivel más alto del Gran Agon. El Altis no tiene palabras — solo esta inscripción.',
    condicion: 'Alcanza el nivel Inmortal (3.900 kleos).',
    icono: '🏛️',
    tipo: 'secreta' as const,
    secreto: true,
  },
  {
    id: 'el_espejo',
    nombre: 'El Espejo',
    descripcion: 'No era probable. No estaba coordinado. Simplemente ocurrió.',
    condicion: 'Ambos agonistas alcanzan el mismo nivel el mismo día.',
    icono: '🪞',
    tipo: 'secreta' as const,
    secreto: true,
  },
  {
    id: 'el_ultimo_agon',
    nombre: 'El Último Agon',
    descripcion: 'Podrías haberte relajado. Marcaste las 7 pruebas igual. Hasta el final.',
    condicion: 'Completa las 7 pruebas el día 29.',
    icono: '🏁',
    tipo: 'secreta' as const,
    secreto: true,
  },
  {
    id: 'la_redencion',
    nombre: 'La Redención',
    descripcion:
      'Cayó en la Disputa. Perdió el rango. Volvió a ganarlo. El Altis no olvida el camino de regreso.',
    condicion:
      'Perder una Disputa de Campeón y recuperar rango Campeón en la misma facción.',
    icono: '🔄',
    tipo: 'secreta' as const,
    secreto: true,
  },
  {
    id: 'el_hegemon_absoluto',
    nombre: 'El Hegemon Absoluto',
    descripcion:
      'Dos tronos. Mismo agonista. La Ciudad entera bajo un solo nombre. El Altis no había visto esto antes.',
    condicion: 'Tener dos facciones en rango Campeón simultáneamente.',
    icono: '👑',
    tipo: 'secreta' as const,
    secreto: true,
  },
  {
    id: 'la_marca_del_traidor',
    nombre: 'La Marca del Traidor',
    descripcion:
      'Dos veces la Ciudad te vio caer. Dos veces la marca quedó. El Altis no juzga — solo registra.',
    condicion: 'Acumular 2 traiciones (traicion_count = 2).',
    icono: '🩸',
    tipo: 'secreta' as const,
    secreto: true,
  },
  {
    id: 'el_sacrificio',
    nombre: 'El Sacrificio',
    descripcion:
      'Nadie lo pidió. Nadie lo vio venir. El agonista entregó algo real sin saber qué recibiría a cambio.',
    condicion: 'Ejecutar un sacrificio asimétrico voluntario en una Crisis tipo H.',
    icono: '🕯️',
    tipo: 'secreta' as const,
    secreto: true,
  },

  // ─── EASTER EGGS (25) ─────────────────────────────
  {
    id: 'el_boxeador_de_philadelphia',
    nombre: 'El Boxeador de Philadelphia',
    descripcion: 'Subiste las escaleras corriendo. Llegaste arriba con los brazos en alto. Nadie te vio. El Altis sí.',
    condicion: 'Registra gym + cardio + 10.000 pasos antes de las 8am.',
    icono: '🥊',
    tipo: 'easter_egg' as const,
    secreto: true,
  },
  {
    id: 'espartanos_cual_es_su_oficio',
    nombre: 'Espartanos, ¿Cuál es Vuestro Oficio?',
    descripcion: '¿Cuál es tu oficio? Acumular kleos. Esta noche cenamos en el Altis.',
    condicion: 'Acumula exactamente 300 kleos en un solo día.',
    icono: '🛡️',
    tipo: 'easter_egg' as const,
    secreto: true,
  },
  {
    id: 'no_estas_entretenido',
    nombre: '¿No Estás Entretenido?',
    descripcion: 'El pulgar apuntó hacia arriba. Las siete pruebas estaban completas. El domingo no fue un día de descanso — fue un día de gloria.',
    condicion: 'Completa las 7 pruebas un domingo.',
    icono: '🏟️',
    tipo: 'easter_egg' as const,
    secreto: true,
  },
  {
    id: 'el_fantasma_de_esparta',
    nombre: 'El Fantasma de Esparta',
    descripcion: 'Las cadenas que cargaba pesaban más que cualquier barra. Aun así entrenó. Cinco veces hiciste lo mismo sin que nadie te lo pidiera.',
    condicion: 'Registra gym + cardio + 10.000 pasos el mismo día, 5 veces totales.',
    icono: '👻',
    tipo: 'easter_egg' as const,
    secreto: true,
  },
  {
    id: 'winter_is_coming',
    nombre: 'Winter is Coming',
    descripcion: 'El señor de la casa lo repitió tanto que nadie le creyó. Tú sí estabas listo cuando llegó.',
    condicion: 'Completa todas las pruebas durante una Semana Sagrada completa.',
    icono: '❄️',
    tipo: 'easter_egg' as const,
    secreto: true,
  },
  {
    id: 'yo_soy_el_peligro',
    nombre: 'Yo Soy el Peligro',
    descripcion: 'Tocó la puerta. Era él. Siete mañanas seguidas fue el primero. El antagonista aprendió a no preguntar quién llega primero.',
    condicion: 'Sé el primero en registrar una prueba del día durante 7 días consecutivos.',
    icono: '⚗️',
    tipo: 'easter_egg' as const,
    secreto: true,
  },
  {
    id: 'un_agon_para_gobernarlos',
    nombre: 'Un Agon para Gobernarlos a Todos',
    descripcion: 'Fue arrojado al fuego y no se destruyó. Cayó cinco veces en la oscuridad y aun así llegó a la montaña.',
    condicion: 'Falla 5 días totales y completa el día 29 con las 7 pruebas.',
    icono: '💍',
    tipo: 'easter_egg' as const,
    secreto: true,
  },
  {
    id: 'cada_intento_es_un_escape',
    nombre: 'Cada Intento es un Escape',
    descripcion: 'Murió. Volvió al principio. Lo intentó de nuevo. Esta vez las siete puertas se abrieron.',
    condicion: 'Falla un día completo y al día siguiente logra un día perfecto.',
    icono: '🗡️',
    tipo: 'easter_egg' as const,
    secreto: true,
  },
  {
    id: 'atrapalos_a_todos',
    nombre: 'Atrápelos a Todos',
    descripcion: 'Salió con una mochila, una meta y ningún plan. Volvió con cinco. El Altis nunca había visto eso en un solo día.',
    condicion: 'Desbloquea 5 inscripciones en 24 horas.',
    icono: '🎮',
    tipo: 'easter_egg' as const,
    secreto: true,
  },
  {
    id: 'red_pill_or_blue_pill',
    nombre: 'Red Pill or Blue Pill',
    descripcion: 'Uno abrió los ojos. El otro eligió seguir durmiendo. El Altis registró exactamente lo que cada uno decidió ver.',
    condicion: 'Completa las 7 pruebas el mismo día que el antagonista completa 0.',
    icono: '💊',
    tipo: 'easter_egg' as const,
    secreto: true,
  },
  {
    id: 'boogeyman',
    nombre: 'Boogeyman',
    descripcion: 'Todos sabían que volvería. Nadie sabía exactamente cuándo. Al día siguiente estaban las siete pruebas completas.',
    condicion: 'Completa las 7 pruebas el día después de haber fallado un día completo.',
    icono: '👁️',
    tipo: 'easter_egg' as const,
    secreto: true,
  },
  {
    id: 'not_my_tempo',
    nombre: 'Not My Tempo',
    descripcion: 'Había alguien en la sala que nunca estaba satisfecho con el ritmo. Seis días seguidos de gimnasio. Ahora el Altis tampoco lo está.',
    condicion: 'Registra gym 6 días consecutivos.',
    icono: '🥁',
    tipo: 'easter_egg' as const,
    secreto: true,
  },
  {
    id: 'moneyball',
    nombre: 'MoneyBall',
    descripcion: 'Los números generales decían que iba perdiendo. Los números de esa semana decían otra cosa.',
    condicion: 'Gana una Hegemonía teniendo menos kleos totales que el antagonista.',
    icono: '⚾',
    tipo: 'easter_egg' as const,
    secreto: true,
  },
  {
    id: 'thats_what_she_said',
    nombre: "That's What She Said",
    descripcion: 'Dijo que lo haría el lunes. Y lo hizo. El Altis no esperaba eso de un lunes.',
    condicion: 'Completa las 7 pruebas un lunes.',
    icono: '📋',
    tipo: 'easter_egg' as const,
    secreto: true,
  },
  {
    id: 'la_especia_debe_fluir',
    nombre: 'La Especia debe Fluir',
    descripcion: 'Hay un recurso sin el cual nada funciona. Llegó al nivel más alto sin soltarlo ni un día.',
    condicion: 'Alcanza nivel Semidiós sin haber fallado la prueba de agua ningún día.',
    icono: '🏜️',
    tipo: 'easter_egg' as const,
    secreto: true,
  },
  {
    id: 'may_the_fourth',
    nombre: 'May the Fourth Be With You',
    descripcion: 'Nadie planifica esto. Nadie lo busca. La fuerza estuvo contigo ese día.',
    condicion: 'Completa las 7 pruebas el día 4 del agon.',
    icono: '⭐',
    tipo: 'easter_egg' as const,
    secreto: true,
  },
  {
    id: 'le_hice_una_oferta',
    nombre: 'Le Hice una Oferta que no Pudo Rechazar',
    descripcion: 'La envió a medianoche. Sin previo aviso. El antagonista la encontró al despertar.',
    condicion: 'Envía una provocación entre las 00:00 y las 00:01.',
    icono: '🌹',
    tipo: 'easter_egg' as const,
    secreto: true,
  },
  {
    id: 'daniel_san',
    nombre: 'Daniel San',
    descripcion: 'El maestro no explicó por qué. Siete días, siete pruebas, sin preguntar para qué. Al octavo día lo entendió todo.',
    condicion: 'Completa los 7 hábitos los primeros 7 días consecutivos del agon.',
    icono: '🥋',
    tipo: 'easter_egg' as const,
    secreto: true,
  },
  {
    id: 'primera_regla_del_agon',
    nombre: '¿Cuál es la Primera Regla del Agon?',
    descripcion: 'Siete días de kleos acumulado en silencio total. La primera regla se cumplió. La segunda también.',
    condicion: 'No publiques nada en el Ágora los primeros 7 días completando todas las pruebas.',
    icono: '🤫',
    tipo: 'easter_egg' as const,
    secreto: true,
  },
  {
    id: 'dont_let_him_leave_murph',
    nombre: "Don't Let Him Leave Murph",
    descripcion: 'A millones de kilómetros de distancia, en tiempos distintos, dos personas tomaron las mismas decisiones el mismo día.',
    condicion: 'Completa exactamente las mismas 7 pruebas que el antagonista el mismo día.',
    icono: '🌌',
    tipo: 'easter_egg' as const,
    secreto: true,
  },
  {
    id: 'el_orgullo_de_philadelphia',
    nombre: 'El Orgullo de Philadelphia',
    descripcion: 'La primera vez fue difícil. La décima vez ya era costumbre. Hay una ciudad que entiende exactamente lo que eso significa.',
    condicion: 'Registra gym + cardio + 10.000 pasos el mismo día, 10 veces totales.',
    icono: '🏙️',
    tipo: 'easter_egg' as const,
    secreto: true,
  },
  {
    id: 'run_agonista_run',
    nombre: 'Run, Agonista, Run',
    descripcion: 'Un día simplemente empezó a caminar. Luego a correr. No paró por diez días. El Altis nunca supo exactamente por qué.',
    condicion: 'Registra 10.000+ pasos durante 10 días consecutivos.',
    icono: '🌾',
    tipo: 'easter_egg' as const,
    secreto: true,
  },
  {
    id: 'por_troya',
    nombre: 'Por Troya',
    descripcion: 'Las guerras no siempre se ganan por aplastamiento. A veces un solo kleos separa la gloria del olvido.',
    condicion: 'Gana una Hegemonía con exactamente 1 kleos de diferencia.',
    icono: '🏛️',
    tipo: 'easter_egg' as const,
    secreto: true,
  },
  {
    id: 'algunos_hombres',
    nombre: 'Algunos Hombres Solo Quieren Ver el Mundo Arder',
    descripcion: 'Ese día tú elegiste las siete pruebas. El antagonista eligió el caos.',
    condicion: 'Completa un día perfecto el mismo día que el antagonista completa 0 pruebas.',
    icono: '🃏',
    tipo: 'easter_egg' as const,
    secreto: true,
  },
  {
    id: 'di_hola_a_mi_pequeno_amigo',
    nombre: 'Di Hola a mi Pequeño Amigo',
    descripcion: 'Llegó lejos. Más lejos de lo que nadie esperaba. El día que nadie vio venir fue el mejor día del agon.',
    condicion: 'Acumula más kleos en un día que en cualquier otro día previo, después del día 20.',
    icono: '🌺',
    tipo: 'easter_egg' as const,
    secreto: true,
  },
  {
    id: 'when_you_play_the_game',
    nombre: 'When You Play the Game of Thrones',
    descripcion:
      'Dos reclamaron el mismo trono. Solo uno lo conservó. El otro aprendió que en este juego no hay empates.',
    condicion: 'Ganar una Disputa de Campeón.',
    icono: '🐉',
    tipo: 'easter_egg' as const,
    secreto: true,
  },
  {
    id: 'jamal_malik',
    nombre: 'Jamal Malik',
    descripcion:
      'No estudió para esto. No lo prepararon para esto. Respondió desde lo que vivió. Y ganó.',
    condicion: 'Ganar una apuesta de trivia en una Crisis tipo F.',
    icono: '📺',
    tipo: 'easter_egg' as const,
    secreto: true,
  },
  {
    id: 'mision_imposible',
    nombre: 'Su Misión, si Decide Aceptarla',
    descripcion:
      'Cuatro crisis. Cuatro veces el expediente decía que no podía completarse. Cuatro veces se equivocó el expediente.',
    condicion: 'Resolver las 4 crisis del reto.',
    icono: '💣',
    tipo: 'easter_egg' as const,
    secreto: true,
  },
  {
    id: 'sin_tiempo_para_morir',
    nombre: 'Sin Tiempo Para Morir',
    descripcion:
      'La ventana se abría por horas. Podría haberla ignorado. Eligió no hacerlo. El Altis registra a los agentes que actúan cuando otros dudan.',
    condicion: 'Completar una prueba Destino de dificultad difícil.',
    icono: '🔫',
    tipo: 'easter_egg' as const,
    secreto: true,
  },
] as const

export type InscripcionId = (typeof INSCRIPCIONES)[number]['id']
export type InscripcionTipo = (typeof INSCRIPCIONES)[number]['tipo']
